apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-template.fullname" . }}-conf
  labels:
    {{- include "helm-template.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.settings }}
  {{ $key }}: {{ $value | squote }}
{{- end }}