SHEP_IS_IGNORE_WSS: "true"
SHEP_IS_WSS_USING: "true"
SHEP_SENDER_ID: centercredit
SHEP_SERVICE_ID: CITS_DEBTS
SHEP_SIGN_KEY_IDENTIFIER: X509_KEY_IDENTIFIER
SHEP_SIGN_KEY_PATH: /app/cert/gost.p12
SHEP_SIGN_KEY_TYPE: PKCS12
SHEP_URL: http://195.12.113.7/bip-sync-wss-gost/